### ISSUE TITLE
working on record.py 

### ISSUE THREAD

**Issue by heyitsalina** [heyitsalina/mpt_facetracking#1]
hey everbody

i looked through the different files and frameworks we were given and i think it'd be best if everyone of us takes over one file that needs to be coded.

for this issue i'm talking about the **record.py file** which also includes a lot of tutorials/resources we were given
**who wants to get started for this file? :)**
@sekkurocode 
@ModusMorris

**Comment by heyitsalina** [comment]
to be real and if nobody has anything against it, i would start with this file myself 🤓

**Comment by sekkurocode** [comment]
Sure go ahead. I like the enthusiasm HAHAHA B)
