### ISSUE TITLE
working on crop.py

### ISSUE THREAD

**Issue by heyitsalina** [heyitsalina/mpt_facetracking#3]
hey everbody

i looked through the different files and frameworks we were given and i think it'd be best if everyone of us takes over one file that needs to be coded.

for this issue i'm talking about the crop.py file which also includes a lot of tutorials/resources we were given
who wants to get started for this file? :)
@sekkurocode
@ModusMorris

**Comment by ModusMorris** [comment]
I take this one

**Comment by ModusMorris** [comment]
Folders are created, files are deleted from the training and Val folder. 
Pictures get a border which is mirrored, we have to check which value would be best. 
The next step is to cut and move the files into the target folder
